const nodemailer = require('nodemailer');

/**
 * Send an enterprise inquiry email to the partnership team
 * and optionally send an acknowledgment confirmation email to the user.
 */
const sendEnterpriseInquiryEmail = async ({ name, email, company, phone, message }) => {
  const smtpHost = process.env.SMTP_HOST;
  const smtpPort = process.env.SMTP_PORT || 587;
  const smtpUser = process.env.SMTP_USER;
  const smtpPass = process.env.SMTP_PASS;
  const smtpSecure = process.env.SMTP_SECURE === 'true' || smtpPort === '465';
  const contactEmail = process.env.CONTACT_EMAIL || 'contact@myscribble.in';

  // If SMTP configs are not defined, log the details and return gracefully
  if (!smtpHost || !smtpUser || !smtpPass) {
    console.warn('[EmailService] ⚠️ SMTP configuration is missing in .env. Logging inquiry details to console instead:');
    console.log('====================================');
    console.log(`TO: ${contactEmail}`);
    console.log(`SUBJECT: 🏢 New Enterprise Inquiry: ${company} - ${name}`);
    console.log(`REPLY-TO: ${email}`);
    console.log('--- CONTENT ---');
    console.log(`Name: ${name}`);
    console.log(`Email: ${email}`);
    console.log(`Company: ${company}`);
    console.log(`Phone: ${phone}`);
    console.log(`Message:\n${message}`);
    console.log('====================================');
    return { success: true, logged: true };
  }

  // Create transporter
  const transporter = nodemailer.createTransport({
    host: smtpHost,
    port: parseInt(smtpPort, 10),
    secure: smtpSecure,
    auth: {
      user: smtpUser,
      pass: smtpPass,
    },
  });

  // 1. Email to partnerships team
  const adminHtml = `
    <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eee; border-radius: 8px;">
      <h2 style="color: #333; border-bottom: 2px solid #00ff66; padding-bottom: 10px;">🏢 New Enterprise Inquiry Received</h2>
      <p style="font-size: 16px; color: #555;">A new inquiry has been submitted from the Scribble Enterprise page:</p>
      
      <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
        <tr>
          <td style="padding: 8px 0; font-weight: bold; width: 150px; color: #666;">Full Name:</td>
          <td style="padding: 8px 0; color: #333;">${name}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; font-weight: bold; color: #666;">Work Email:</td>
          <td style="padding: 8px 0; color: #333;"><a href="mailto:${email}">${email}</a></td>
        </tr>
        <tr>
          <td style="padding: 8px 0; font-weight: bold; color: #666;">Company Name:</td>
          <td style="padding: 8px 0; color: #333;">${company}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; font-weight: bold; color: #666;">Phone Number:</td>
          <td style="padding: 8px 0; color: #333;">${phone}</td>
        </tr>
      </table>

      <h3 style="color: #444; margin-top: 25px;">Area of Interest / Message:</h3>
      <div style="white-space: pre-wrap; background: #f9f9f9; padding: 15px; border-left: 4px solid #00ff66; border-radius: 4px; color: #333; line-height: 1.5;">${message}</div>
      
      <p style="font-size: 12px; color: #999; margin-top: 30px; border-top: 1px solid #eee; padding-top: 10px;">
        This email was automatically generated by the Scribble Localhost Server.
      </p>
    </div>
  `;

  await transporter.sendMail({
    from: `"${name} (via Scribble)" <${smtpUser}>`,
    to: contactEmail,
    replyTo: email,
    subject: `🏢 New Enterprise Inquiry: ${company} - ${name}`,
    html: adminHtml,
  });

  console.log(`[EmailService] ✅ Admin notification email sent to ${contactEmail}`);

  // 2. Acknowledgment email to the customer
  try {
    const customerHtml = `
      <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eee; border-radius: 8px;">
        <h2 style="color: #6c5ce7; border-bottom: 2px solid #6c5ce7; padding-bottom: 10px;">✨ Thank you for reaching out to Scribble!</h2>
        <p style="font-size: 16px; color: #333; line-height: 1.5;">Hi ${name},</p>
        <p style="font-size: 15px; color: #555; line-height: 1.5;">
          We have received your enterprise inquiry. Our partnerships team is currently reviewing your details and will get back to you within 24 business hours.
        </p>
        
        <div style="background: #fcfcfc; border: 1px solid #f0f0f0; border-radius: 6px; padding: 15px; margin: 20px 0;">
          <h4 style="margin-top: 0; color: #444;">Summary of details received:</h4>
          <ul style="list-style: none; padding: 0; margin: 0; color: #555; line-height: 1.6;">
            <li><strong>Company Name:</strong> ${company}</li>
            <li><strong>Phone:</strong> ${phone}</li>
            <li><strong>Interest Area:</strong> ${message.length > 80 ? message.substring(0, 80) + '...' : message}</li>
          </ul>
        </div>

        <p style="font-size: 15px; color: #555; line-height: 1.5;">
          If you have any urgent files or updates to share, you can reply directly to this email.
        </p>

        <p style="font-size: 15px; color: #333; margin-top: 25px;">
          Best regards,<br/>
          <strong>Scribble Partnerships Team</strong>
        </p>
      </div>
    `;

    await transporter.sendMail({
      from: `"Scribble Partnerships" <${smtpUser}>`,
      to: email,
      subject: `✨ We've received your enterprise inquiry!`,
      html: customerHtml,
    });

    console.log(`[EmailService] ✅ Customer confirmation email sent to ${email}`);
  } catch (err) {
    console.warn(`[EmailService] ⚠️ Failed to send confirmation email to customer: ${err.message}`);
  }

  return { success: true };
};

module.exports = {
  sendEnterpriseInquiryEmail,
};
